# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ejavier- <ejavier-@student.42porto.com>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/06/27 19:04:26 by ejavier-          #+#    #+#              #
#    Updated: 2025/06/27 19:05:53 by ejavier-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = so_long.a

CC = cc
CFLAGS = -Wall -Wextra -Werror
INCLUDES = -Ilibft

SRCS = ft_printf.c data_print.c data_type.c ft_itoa_base.c print_ptr.c\
print_hexa.c
OBJS = $(SRCS:.c=.o)

AR = ar rcs
RM = rm -f

LIBFT = libft/libft.a

all: $(LIBFT) $(NAME)

$(LIBFT):
	$(MAKE) -C libft
	cp libft/libft.a .
	mv libft.a $(NAME)

$(NAME): $(OBJS)
	$(AR) $(NAME) $(OBJS) libft/libft.a

%.o: %.c
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@
	
clean:
	$(RM) $(OBJS)
	$(MAKE) -C libft clean

fclean: clean
	$(RM) $(NAME)
	$(MAKE) -C libft fclean

re: fclean all